version: '3.7'

services:
  web:
    build: .
    container_name: customer_auth_service
    image: customer_auth_service
    restart: on-failure
    links:
      - cas_mongodb
    environment:
      - SERVER_PORT=8081
      - SERVER_ADDRESS=0.0.0.0
      - MONGODB_URI=mongodb://cas_user:secret@cas_mongodb:27017/cas_mongodb?authSource=admin
      - MONGODB_STATUS_HOST=cas_mongodb
      - MONGODB_STATUS_PORT=27017
    ports:
      - "8081:8081"
    depends_on:
      - cas_mongodb

  cas_mongodb:
    image: mongo:latest
    container_name: cas_mongodb
    hostname: cas_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: cas_mongodb
      MONGO_INITDB_ROOT_USERNAME: cas_user
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - "./data/db:/data/db"