version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: cas_mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cas_db
      MONGO_INITDB_ROOT_USERNAME: cas_user
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - "./data/db:/data/db"
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge
